services:
  # Backend API service
  - type: web
    name: boardgamecreator
    env: node
    buildCommand: cd server && npm install --production=false && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://tabletopstudio.onrender.com
      - key: NODE_ENV
        value: production

  # Frontend static site
  - type: web
    name: tabletopstudio
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://boardgamecreator.onrender.com
      - key: NODE_ENV
        value: production 